version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
      - ./db.bkp/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_root_password
      - MYSQL_PASSWORD=/run/secrets/db_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    secrets:
      - db_root_password
      - db_password

  app:
    image: nextcloud:27-fpm
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /mnt/md126/www/nextcloud11/data/:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=/run/secrets/db_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    secrets:
      - db_password

  web:
    image: nginx
    ports:
      - 8443:443
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    volumes_from:
      - app

secrets:
  db_password:
    file: next_db_password.txt
  db_root_password:
    file: next_db_root_password.txt
