services:
  nextcloudpi:
    image: ownyourbits/nextcloudpi-armhf
    command: "${IP}"
    ports:
     - "9080:80"
     - "443:443"
     - "4443:4443"
    volumes:
     - ./data:/data
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 300M
    container_name: nextcloudpi
