services:
  nextcloudpi:
    image: ownyourbits/nextcloudpi-armhf
    command: "${IP}"
    ports:
     - "9080:80"
     - "9443:443"
     - "9943:4443"
    volumes:
     - ./data:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 400M
    container_name: nextcloudpi
